### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by MichaelSchwar3** [christiancashiola/Stellar#2]
Great work on the sample state!

Just minor things I can be nitpicky about.

- [x] Add Sample State link to your home page

- [x] Capitalize the links on the right side of your Wiki

**Comment by christiancashiola** [comment]
I got you Michael. Addressed those two issues and added my backed/front end routes. It looked sloppy copying the same lines over again so I kind of used a variable... You'll see, it looks clean.
